### ISSUE TITLE
[FEATURE] Add gitpod preview

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/nextjs-dapp-template#2]
### Detailed description

Add gitpod to quick contribute into this project

### Context

Add gitpod to quick contribute into this project

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KukretiShubham** [comment]
agree.

**Comment by mkubdev** [comment]
You can add this button :

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/web3community/nextjs-dapp-template/)

Code : 
```md
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/web3community/nextjs-dapp-template/)
```

And add the gitpod.yaml deploy script : [Help Gitpod understand your repository](https://www.gitpod.io/docs/getting-started#help-gitpod-understand-your-repository)

**Comment by KukretiShubham** [comment]
would you like to create a PR?

**Comment by mkubdev** [comment]
Nop, let folks do it. :) Easy first PR.

**Comment by hyomiTheTech** [comment]
Hi! can I do this task?

**Comment by KukretiShubham** [comment]
yes, go ahead

**Comment by hyomiTheTech** [comment]
> You can add this button :
> 
> [![Open in Gitpod](https://camo.githubusercontent.com/76e60919474807718793857d8eb615e7a50b18b04050577e5a35c19421f260a3/68747470733a2f2f676974706f642e696f2f627574746f6e2f6f70656e2d696e2d676974706f642e737667)](https://gitpod.io/#https://github.com/web3community/nextjs-dapp-template/)
> 
> Code :
> 
> ```lisp
> [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/web3community/nextjs-dapp-template/)
> ```
> 
> And add the gitpod.yaml deploy script : [Help Gitpod understand your repository](https://www.gitpod.io/docs/getting-started#help-gitpod-understand-your-repository)

I created a basic init script at gitpod.yml, but where can I find the deploy script?

**Comment by hyomiTheTech** [comment]
> yes, go ahead

Hi, I made a pull request a couple of days ago. Any feed backs?
